version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # 假設 pyproject.toml 或 requirements.txt 在根目錄
    schedule:
      interval: "weekly"  # 每週一次
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "security"
